#ifndef STACK_CONSTANTS
#define STACK_CONSTANTS
#define STACK_LEFT_VALUE 0x01
#define STACK_RIGHT_VALUE 0x02
#define STACK_RESULT_VALUE 0x00
#define RIGHT_OPERAND_CALCULATED 0x04
#define LEFT_OPERAND_CALCULATED 0X08

#endif